### PR TITLE
Implements ribbon chart example from plotly

### PR DESCRIPTION
**Pull request by jacekpapiniak**
Adds Ribbon example from plotly web site: https://plotly.com/javascript/ribbon-plots/

### CODE REVIEW

**Comment by centreboard** [comment]
The issue is it loads the snippet from GitHub master branch (which I believe now forwards to `main`)
So you can't preview code snippets when running locally.
https://github.com/LayTec-AG/Plotly.Blazor/blob/b83753b7accff5d208b1c01404be71539c66d1b4/Plotly.Blazor.Examples/Shared/CodeSnippet.razor#L15
https://github.com/LayTec-AG/Plotly.Blazor/blob/b83753b7accff5d208b1c01404be71539c66d1b4/Plotly.Blazor.Examples/Startup.cs#L55-L58

A quick fix would be to try catch the web call so it renders a not found message instead of crashing?

**Comment by sean-mcl** [comment]
Feel free to add the try/catch block if you want. I will accept the PR when you’re ready.

Thank you for your contribution 🤝😄

**Comment by jacekpapiniak** [comment]
@sean-mcl & @centreboard thanks for a tip and clarification on the problem. I have added try catch to **CodeSnippet** component so we print error in console.

It should be ready to review now.

**Comment by sean-mcl** [comment]
> @sean-mcl & @centreboard thanks for a tip and clarification on the problem. I have added try catch to **CodeSnippet** component so we print error in console.
> 
> It should be ready to review now.

There is still a merge conflict.

**Comment by jacekpapiniak** [comment]
> > @sean-mcl & @centreboard thanks for a tip and clarification on the problem. I have added try catch to **CodeSnippet** component so we print error in console.
> > It should be ready to review now.
> 
> There is still a merge conflict.

Ah yes, sorry @sean-mcl. It is quite interesting, as I am trying to merge master into this branch to resolve this conflict but it says it is up to date  with master and it does not highlight any merge conflict. Any ideas?

**Comment by centreboard** [comment]
If you go to https://github.com/jacekpapiniak/Plotly.Blazor/tree/master there should by a button to fetch upstream. This will bring the main branch in your fork upto date with this repo. You can then fetch and merge/rebase locally.

**Comment by jacekpapiniak** [comment]
> If you go to https://github.com/jacekpapiniak/Plotly.Blazor/tree/master there should by a button to fetch upstream. This will bring the main branch in your fork upto date with this repo. You can then fetch and merge/rebase locally.

@sean-mcl Thansks! Sorted 🤝😄

**Comment by jacekpapiniak** [comment]
@sean-mcl could just reminding myself, could I get review please?

**Pull request merged**
